import { Encode_Sans_Expanded } from "next/font/google";
import "./globals.css";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css"
import { Metadata } from "next";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import GlobalLoader from "@/component/GlobalLoader";
import  Providers from "../providers/Components/ReactQueryProvider.Provider"
import NextAuthProvider from "../providers/Components/nextauth.providers";
  import { ToastContainer} from 'react-toastify';

const Encode = Encode_Sans_Expanded({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
        <body className={Encode.className}>

        <GlobalLoader/>
        <ToastContainer></ToastContainer>
        <Providers>
          <div  className="flex  flex-col   min-h-screen">

            <NextAuthProvider>
            <Navbar />

             <main className="container  flex-1    mx-auto p-6">{children}</main>


          <Footer/>

          </NextAuthProvider>
          </div>

         </Providers>
        </body>
      </html>
  
  );
}
